from ..type.item import *

class Items:
    copper = Item('copper')
    lead = Item('lead')
    metaglass = Item('metaglass')
    graphite = Item('graphite')
    sand = Item('sand')
    coal = Item('coal')
    titanium = Item('titanium')
    thorium = Item('thorium')
    scrap = Item('scrap')
    silicon = Item('silicon')
    plastanium = Item('plastanium')
    phaseFabric = Item('phase-fabric')
    phaseFabric = Item('phase-fabric')
    surgeAlloy = Item('surge-alloy')
    sporePod = Item('spore-pod')
    blastCompound = Item('blast-compound')
    pyratite = Item('pyratite')
    beryllium = Item('beryllium')
    tungsten = Item('tungsten')
    oxide = Item('oxide')
    carbide = Item('carbide')
    fissileMatter = Item('fissile-matter')
    dormantCyst = Item('dormant-cyst')