from ..type.status_effect import *

class StatusEffects:
    none = StatusEffect("none")
    burning = StatusEffect("burning")
    freezing = StatusEffect("freezing")
    unmoving = StatusEffect("unmoving")
    slow = StatusEffect("slow")
    fast = StatusEffect("fast")
    wet = StatusEffect("wet")
    muddy = StatusEffect("muddy")
    melting = StatusEffect("melting")
    sapped = StatusEffect("sapped")
    electrified = StatusEffect("electrified")
    spore_slowed = StatusEffect("spore-slowed")
    tarred = StatusEffect("tarred")
    overdrive = StatusEffect("overdrive")
    overclock = StatusEffect("overclock")
    shielded = StatusEffect("shielded")
    boss = StatusEffect("boss")
    shocked = StatusEffect("shocked")
    blasted = StatusEffect("blasted")
    corroded = StatusEffect("corroded")
    disarmed = StatusEffect("disarmed")
    invincible = StatusEffect("invincible")
    dynamic = StatusEffect("dynamic")